# Image resolution
resolution: { width: 3280, height: 2464 }

isloaded: yes

# Path to save images
filePath: /home/pi/raspberry-timelapse/test/

# Filename prefix
# <prefix>_07-08-2019_23.40.01.jpg
filePrefix: timelapse

# Interval in seconds
# Take a picture every <interval> second
interval: 4

# ISO value. 0 = auto, 60-800 for manual ISO.
iso: 400

# Shutter speed. 0 = auto, else value in microseconds (seconds * 1000000).
shutter_speed: 6000000

# White balance. Set to empty object (`{ }`) to use auto white balance.
#white_balance: { }
white_balance: { red_gain: 1.3, blue_gain: 3 }