# Image resolution
resolution: { width: 3280, height: 2464 }

isloaded: yes

# Path to save images
filePath: /home/pi/raspberry-timelapse/test/

# Filename prefix
# <prefix>_07-08-2019_23.40.01.jpg
filePrefix: timelapse

# Interval in seconds
# Take a picture every <interval> second
interval: 10

