# Image resolution
resolution: { width: 3280, height: 2464 }

isloaded: yes

# Path to save images
filePath: /var/www/html/bilder/
frameRate: 0.5
# Filename prefix
# <prefix>_07-08-2019_23.40.01.jpg
filePrefix: timelapse

# Interval in seconds
# Take a picture every <interval> second
interval: 15

# ISO value. 0 = auto, 60-800 for manual ISO.
iso: 800

# Shutter speed. 0 = auto, else value in microseconds (seconds * 1000000).
shutter_speed: 0 

# White balance. Set to empty object (`{ }`) to use auto white balance.
#white_balance: { }
#white_balance: { red_gain: 1.4, blue_gain: 1 }
