# Configuration
isloaded: yes

# Image resolution
# resolution: { width: 3280, height: 2464 } // full resolution
resolution: { width: 1198, height: 900 }

# Path to save images
filePath: /var/www/html/bilder/
frameRate: 0.5
# Filename prefix
# <prefix>_07-08-2019_23.40.01.jpg
filePrefix: sortland_cam_01

# Interval in seconds
# Take a picture every <interval> second
interval: 30

# ISO value. 0 = auto, 60-800 for manual ISO.
iso: 800

# Metering mode to determine exposure: average, spot, backlit, matrix
metering: 'backlit' 

# Exposure mode
# exposure_mode: 'night'
exposure_mode: 'night'

# Shutter speed. 0 = auto, else value in microseconds (seconds * 1000000).
shutter_speed: 6000000 

# White balance. Set to empty object (`{ }`) to use auto white balance.
white_balance: "off"
white_balance_gain: { red_gain: 1.6, blue_gain: 1.7 }

# Copy last taken image to status image
copy_last: true
status_filename: /var/www/html/status.jpg
